spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb
    username: root
    password: mc07139218..
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: club.musician.userrole.entity

logging:
  level:
    club.musician.userrole.dao: debug
